name: run scrape2.R

on:
  schedule:
    - cron: '0 0 1 * *' # runs at 12:00 UTC once a month

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup R
          uses: r-lib/actions/setup-r@v2
          with:
          r-version: '4.1.0' # install the R version needed
          
      - name: install R packages
        run: |
          Rscript -e 'install.packages(c("tidyverse", "rvest"))'
          
      - name: execute R script # run scrape2.R
        run: Rscript scrape2.R
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
